# -*- coding: utf-8 -*-
"""DFS_New.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8TgexF5mp3Sw-QxqO8YGq2Xhaen2Ntw
"""

import time
import sys
import tracemalloc

sys.setrecursionlimit(100000)

def is_safe(board, row, col):

    for i in range(row):

        if board[i] == col or \
           board[i] - i == col - row or \
           board[i] + i == col + row:
            return False

    return True

def dfs_nqueen(n, time_limit=None):

    board = [-1] * n

    solution_found = False

    start_time = time.time()

    def solve(row):

        nonlocal solution_found

        # TIME LIMIT CHECK
        if time_limit is not None:
            if time.time() - start_time > time_limit:
                return "timeout"

        # SOLUTION FOUND
        if row == n:
            solution_found = True
            return "solved"

        for col in range(n):

            if is_safe(board, row, col):

                board[row] = col

                result = solve(row + 1)

                if result == "solved":
                    return "solved"

                if result == "timeout":
                    return "timeout"

                board[row] = -1

        return "continue"

    status = solve(0)

    return board, solution_found, status

def run_dfs(n):

    print("\n================================================")
    print(f"DFS / Backtracking for N = {n}")
    print("================================================")

    tracemalloc.start()

    start = time.time()

    # TIME LIMIT SETTINGS
    if n == 10:
        limit = 30

    elif n == 30:
        limit = 3000     # NO TIME LIMIT

    else:
        limit = 300        # timeout for large N

    try:

        solution, solved, status = dfs_nqueen(n, limit)

    except Exception as e:

        solution = []
        solved = False
        status = f"Error: {str(e)}"

    end = time.time()

    current, peak = tracemalloc.get_traced_memory()

    tracemalloc.stop()

    # FINAL STATUS
    if status == "timeout":
        final_status = "Timeout"

    elif solved:
        final_status = "Completed"

    else:
        final_status = "Failed"

    print("Solved:", solved)

    if solved:
        print("Solution:", solution[:min(20, len(solution))], "...")
    else:
        print("Solution: Not Found")

    print("Time (sec):", round(end - start, 4))

    print("Memory (KB):", round(peak / 1024, 2))

    print("Status:", final_status)

test_values = [10, 30, 50, 100, 200, 500]

for n in test_values:

    run_dfs(n)